# CMake generated Testfile for 
# Source directory: /Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests
# Build directory: /Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ecm_add_tests-single_tests "/usr/local/Cellar/cmake/3.21.0/bin/ctest" "--build-and-test" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/single_tests" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/single_tests" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "single_tests" "--build-options" "-DBUILD_TESTING:BOOL=ON" "--test-command" "/usr/local/Cellar/cmake/3.21.0/bin/ctest")
set_tests_properties(ecm_add_tests-single_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;4;add_test;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;30;add_check;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;0;")
add_test(ecm_add_tests_did_run-single_tests "/usr/local/Cellar/cmake/3.21.0/bin/cmake" "-P" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/check_files.cmake" "test1.txt" "test2.txt" "test3.txt" "test4.txt" "test5.txt" "test6.txt")
set_tests_properties(ecm_add_tests_did_run-single_tests PROPERTIES  DEPENDS "ecm_add_tests-single_tests" WORKING_DIRECTORY "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/single_tests" _BACKTRACE_TRIPLES "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;19;add_test;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;30;add_check;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;0;")
add_test(ecm_add_tests-multi_tests "/usr/local/Cellar/cmake/3.21.0/bin/ctest" "--build-and-test" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/multi_tests" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/multi_tests" "--build-two-config" "--build-generator" "Unix Makefiles" "--build-makeprogram" "/usr/bin/make" "--build-project" "multi_tests" "--build-options" "-DBUILD_TESTING:BOOL=ON" "--test-command" "/usr/local/Cellar/cmake/3.21.0/bin/ctest")
set_tests_properties(ecm_add_tests-multi_tests PROPERTIES  _BACKTRACE_TRIPLES "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;4;add_test;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;38;add_check;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;0;")
add_test(ecm_add_tests_did_run-multi_tests "/usr/local/Cellar/cmake/3.21.0/bin/cmake" "-P" "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/check_files.cmake" "test1.txt" "test2.txt" "test3.txt" "test4.txt" "test5.txt" "test6.txt" "test7.txt" "test8.txt" "test9.txt")
set_tests_properties(ecm_add_tests_did_run-multi_tests PROPERTIES  DEPENDS "ecm_add_tests-multi_tests" WORKING_DIRECTORY "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/multi_tests" _BACKTRACE_TRIPLES "/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;19;add_test;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;38;add_check;/Users/benjaminowad/Documents/dev/qView/ci/pwsh/extra-cmake-modules/tests/ECMAddTests/CMakeLists.txt;0;")
